// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertHospital = `-- name: InsertHospital :one
INSERT INTO hospitals
  (name, addresses, location_names, npis, license_number, license_state, version, last_updated_on, attester_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertHospitalParams struct {
	Name          string      `json:"name"`
	Addresses     []string    `json:"addresses"`
	LocationNames []string    `json:"location_names"`
	Npis          []string    `json:"npis"`
	LicenseNumber pgtype.Text `json:"license_number"`
	LicenseState  pgtype.Text `json:"license_state"`
	Version       string      `json:"version"`
	LastUpdatedOn pgtype.Date `json:"last_updated_on"`
	AttesterName  pgtype.Text `json:"attester_name"`
}

func (q *Queries) InsertHospital(ctx context.Context, arg InsertHospitalParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertHospital,
		arg.Name,
		arg.Addresses,
		arg.LocationNames,
		arg.Npis,
		arg.LicenseNumber,
		arg.LicenseState,
		arg.Version,
		arg.LastUpdatedOn,
		arg.AttesterName,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertItemCode = `-- name: InsertItemCode :exec
INSERT INTO item_codes (item_id, code_id)
VALUES ($1, $2)
ON CONFLICT (item_id, code_id) DO NOTHING
`

type InsertItemCodeParams struct {
	ItemID int32 `json:"item_id"`
	CodeID int32 `json:"code_id"`
}

func (q *Queries) InsertItemCode(ctx context.Context, arg InsertItemCodeParams) error {
	_, err := q.db.Exec(ctx, insertItemCode, arg.ItemID, arg.CodeID)
	return err
}

type InsertPayerChargesParams struct {
	StandardChargeID         int32          `json:"standard_charge_id"`
	PayerName                string         `json:"payer_name"`
	PlanID                   int32          `json:"plan_id"`
	Methodology              string         `json:"methodology"`
	StandardChargeDollar     pgtype.Numeric `json:"standard_charge_dollar"`
	StandardChargePercentage pgtype.Numeric `json:"standard_charge_percentage"`
	StandardChargeAlgorithm  pgtype.Text    `json:"standard_charge_algorithm"`
	EstimatedAmount          pgtype.Numeric `json:"estimated_amount"`
	MedianAmount             pgtype.Numeric `json:"median_amount"`
	Percentile10th           pgtype.Numeric `json:"percentile_10th"`
	Percentile90th           pgtype.Numeric `json:"percentile_90th"`
	Count                    pgtype.Text    `json:"count"`
	AdditionalNotes          pgtype.Text    `json:"additional_notes"`
}

const insertStandardCharge = `-- name: InsertStandardCharge :one
INSERT INTO standard_charges
  (item_id, setting, gross_charge, discounted_cash, minimum, maximum, modifier_codes, additional_notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertStandardChargeParams struct {
	ItemID          int32          `json:"item_id"`
	Setting         string         `json:"setting"`
	GrossCharge     pgtype.Numeric `json:"gross_charge"`
	DiscountedCash  pgtype.Numeric `json:"discounted_cash"`
	Minimum         pgtype.Numeric `json:"minimum"`
	Maximum         pgtype.Numeric `json:"maximum"`
	ModifierCodes   []string       `json:"modifier_codes"`
	AdditionalNotes pgtype.Text    `json:"additional_notes"`
}

func (q *Queries) InsertStandardCharge(ctx context.Context, arg InsertStandardChargeParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertStandardCharge,
		arg.ItemID,
		arg.Setting,
		arg.GrossCharge,
		arg.DiscountedCash,
		arg.Minimum,
		arg.Maximum,
		arg.ModifierCodes,
		arg.AdditionalNotes,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertStandardChargeItem = `-- name: InsertStandardChargeItem :one
INSERT INTO standard_charge_items (hospital_id, description, drug_unit, drug_unit_type)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertStandardChargeItemParams struct {
	HospitalID   int32          `json:"hospital_id"`
	Description  string         `json:"description"`
	DrugUnit     pgtype.Numeric `json:"drug_unit"`
	DrugUnitType pgtype.Text    `json:"drug_unit_type"`
}

func (q *Queries) InsertStandardChargeItem(ctx context.Context, arg InsertStandardChargeItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertStandardChargeItem,
		arg.HospitalID,
		arg.Description,
		arg.DrugUnit,
		arg.DrugUnitType,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertCode = `-- name: UpsertCode :one
INSERT INTO codes (code, code_type)
VALUES ($1, $2)
ON CONFLICT (code, code_type) DO UPDATE SET code = EXCLUDED.code
RETURNING id
`

type UpsertCodeParams struct {
	Code     string `json:"code"`
	CodeType string `json:"code_type"`
}

func (q *Queries) UpsertCode(ctx context.Context, arg UpsertCodeParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCode, arg.Code, arg.CodeType)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertPlan = `-- name: UpsertPlan :one
INSERT INTO plans (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) UpsertPlan(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertPlan, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
