// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertHospital(ctx context.Context, arg InsertHospitalParams) (int32, error)
	InsertItemCode(ctx context.Context, arg InsertItemCodeParams) error
	InsertPayerCharges(ctx context.Context, arg []InsertPayerChargesParams) (int64, error)
	InsertStandardCharge(ctx context.Context, arg InsertStandardChargeParams) (int32, error)
	InsertStandardChargeItem(ctx context.Context, arg InsertStandardChargeItemParams) (int32, error)
	UpsertCode(ctx context.Context, arg UpsertCodeParams) (int32, error)
	UpsertPlan(ctx context.Context, name string) (int32, error)
}

var _ Querier = (*Queries)(nil)
