// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertPayerCharges implements pgx.CopyFromSource.
type iteratorForInsertPayerCharges struct {
	rows                 []InsertPayerChargesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPayerCharges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPayerCharges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StandardChargeID,
		r.rows[0].PayerID,
		r.rows[0].PlanID,
		r.rows[0].Methodology,
		r.rows[0].StandardChargeDollar,
		r.rows[0].StandardChargePercentage,
		r.rows[0].StandardChargeAlgorithm,
		r.rows[0].EstimatedAmount,
		r.rows[0].MedianAmount,
		r.rows[0].Percentile10th,
		r.rows[0].Percentile90th,
		r.rows[0].Count,
		r.rows[0].AdditionalNotes,
	}, nil
}

func (r iteratorForInsertPayerCharges) Err() error {
	return nil
}

func (q *Queries) InsertPayerCharges(ctx context.Context, arg []InsertPayerChargesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"payer_charges"}, []string{"standard_charge_id", "payer_id", "plan_id", "methodology", "standard_charge_dollar", "standard_charge_percentage", "standard_charge_algorithm", "estimated_amount", "median_amount", "percentile_10th", "percentile_90th", "count", "additional_notes"}, &iteratorForInsertPayerCharges{rows: arg})
}
