// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Code struct {
	ID       int32  `json:"id"`
	Code     string `json:"code"`
	CodeType string `json:"code_type"`
}

type Hospital struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	Addresses     []string         `json:"addresses"`
	LocationNames []string         `json:"location_names"`
	Npis          []string         `json:"npis"`
	LicenseNumber pgtype.Text      `json:"license_number"`
	LicenseState  pgtype.Text      `json:"license_state"`
	Version       string           `json:"version"`
	LastUpdatedOn pgtype.Date      `json:"last_updated_on"`
	AttesterName  pgtype.Text      `json:"attester_name"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type ItemCode struct {
	ID     int32 `json:"id"`
	ItemID int32 `json:"item_id"`
	CodeID int32 `json:"code_id"`
}

type Modifier struct {
	ID          int32       `json:"id"`
	HospitalID  int32       `json:"hospital_id"`
	Code        string      `json:"code"`
	Description string      `json:"description"`
	Setting     pgtype.Text `json:"setting"`
}

type ModifierPayerInfo struct {
	ID          int32  `json:"id"`
	ModifierID  int32  `json:"modifier_id"`
	PlanID      int32  `json:"plan_id"`
	Description string `json:"description"`
	PayerID     int32  `json:"payer_id"`
}

type Payer struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type PayerCharge struct {
	ID                       int32          `json:"id"`
	StandardChargeID         int32          `json:"standard_charge_id"`
	PlanID                   int32          `json:"plan_id"`
	Methodology              string         `json:"methodology"`
	StandardChargeDollar     pgtype.Numeric `json:"standard_charge_dollar"`
	StandardChargePercentage pgtype.Numeric `json:"standard_charge_percentage"`
	StandardChargeAlgorithm  pgtype.Text    `json:"standard_charge_algorithm"`
	EstimatedAmount          pgtype.Numeric `json:"estimated_amount"`
	MedianAmount             pgtype.Numeric `json:"median_amount"`
	Percentile10th           pgtype.Numeric `json:"percentile_10th"`
	Percentile90th           pgtype.Numeric `json:"percentile_90th"`
	Count                    pgtype.Text    `json:"count"`
	AdditionalNotes          pgtype.Text    `json:"additional_notes"`
	PayerID                  int32          `json:"payer_id"`
}

type Plan struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type StandardCharge struct {
	ID              int32          `json:"id"`
	ItemID          int32          `json:"item_id"`
	Setting         string         `json:"setting"`
	GrossCharge     pgtype.Numeric `json:"gross_charge"`
	DiscountedCash  pgtype.Numeric `json:"discounted_cash"`
	Minimum         pgtype.Numeric `json:"minimum"`
	Maximum         pgtype.Numeric `json:"maximum"`
	ModifierCodes   []string       `json:"modifier_codes"`
	AdditionalNotes pgtype.Text    `json:"additional_notes"`
}

type StandardChargeItem struct {
	ID           int32            `json:"id"`
	HospitalID   int32            `json:"hospital_id"`
	Description  string           `json:"description"`
	DrugUnit     pgtype.Numeric   `json:"drug_unit"`
	DrugUnitType pgtype.Text      `json:"drug_unit_type"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
