// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCodeByCodeAndType = `-- name: GetCodeByCodeAndType :one
SELECT id, code, code_type FROM codes
WHERE code = $1 AND code_type = $2
`

type GetCodeByCodeAndTypeParams struct {
	Code     string `json:"code"`
	CodeType string `json:"code_type"`
}

func (q *Queries) GetCodeByCodeAndType(ctx context.Context, arg GetCodeByCodeAndTypeParams) (Code, error) {
	row := q.db.QueryRow(ctx, getCodeByCodeAndType, arg.Code, arg.CodeType)
	var i Code
	err := row.Scan(&i.ID, &i.Code, &i.CodeType)
	return i, err
}

const getHospitalByName = `-- name: GetHospitalByName :one
SELECT id, name, addresses, location_names, npis, license_number, license_state, version, last_updated_on, attester_name, created_at FROM hospitals WHERE name = $1
`

func (q *Queries) GetHospitalByName(ctx context.Context, name string) (Hospital, error) {
	row := q.db.QueryRow(ctx, getHospitalByName, name)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Addresses,
		&i.LocationNames,
		&i.Npis,
		&i.LicenseNumber,
		&i.LicenseState,
		&i.Version,
		&i.LastUpdatedOn,
		&i.AttesterName,
		&i.CreatedAt,
	)
	return i, err
}

const insertHospital = `-- name: InsertHospital :one
INSERT INTO hospitals (
    name, addresses, location_names, npis,
    license_number, license_state, version,
    last_updated_on, attester_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertHospitalParams struct {
	Name          string      `json:"name"`
	Addresses     []string    `json:"addresses"`
	LocationNames []string    `json:"location_names"`
	Npis          []string    `json:"npis"`
	LicenseNumber pgtype.Text `json:"license_number"`
	LicenseState  pgtype.Text `json:"license_state"`
	Version       string      `json:"version"`
	LastUpdatedOn pgtype.Date `json:"last_updated_on"`
	AttesterName  pgtype.Text `json:"attester_name"`
}

func (q *Queries) InsertHospital(ctx context.Context, arg InsertHospitalParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertHospital,
		arg.Name,
		arg.Addresses,
		arg.LocationNames,
		arg.Npis,
		arg.LicenseNumber,
		arg.LicenseState,
		arg.Version,
		arg.LastUpdatedOn,
		arg.AttesterName,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertItemCode = `-- name: InsertItemCode :exec
INSERT INTO item_codes (item_id, code_id)
VALUES ($1, $2)
ON CONFLICT (item_id, code_id) DO NOTHING
`

type InsertItemCodeParams struct {
	ItemID int32 `json:"item_id"`
	CodeID int32 `json:"code_id"`
}

func (q *Queries) InsertItemCode(ctx context.Context, arg InsertItemCodeParams) error {
	_, err := q.db.Exec(ctx, insertItemCode, arg.ItemID, arg.CodeID)
	return err
}

const insertModifier = `-- name: InsertModifier :one
INSERT INTO modifiers (hospital_id, code, description, setting)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertModifierParams struct {
	HospitalID  int32       `json:"hospital_id"`
	Code        string      `json:"code"`
	Description string      `json:"description"`
	Setting     pgtype.Text `json:"setting"`
}

func (q *Queries) InsertModifier(ctx context.Context, arg InsertModifierParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertModifier,
		arg.HospitalID,
		arg.Code,
		arg.Description,
		arg.Setting,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertModifierPayerInfo = `-- name: InsertModifierPayerInfo :exec
INSERT INTO modifier_payer_info (modifier_id, payer_name, plan_name, description)
VALUES ($1, $2, $3, $4)
`

type InsertModifierPayerInfoParams struct {
	ModifierID  int32  `json:"modifier_id"`
	PayerName   string `json:"payer_name"`
	PlanName    string `json:"plan_name"`
	Description string `json:"description"`
}

func (q *Queries) InsertModifierPayerInfo(ctx context.Context, arg InsertModifierPayerInfoParams) error {
	_, err := q.db.Exec(ctx, insertModifierPayerInfo,
		arg.ModifierID,
		arg.PayerName,
		arg.PlanName,
		arg.Description,
	)
	return err
}

const insertPayerCharge = `-- name: InsertPayerCharge :exec
INSERT INTO payer_charges (
    standard_charge_id, payer_name, plan_name, methodology,
    standard_charge_dollar, standard_charge_percentage,
    standard_charge_algorithm, estimated_amount, median_amount,
    percentile_10th, percentile_90th, count, additional_notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertPayerChargeParams struct {
	StandardChargeID         int32          `json:"standard_charge_id"`
	PayerName                string         `json:"payer_name"`
	PlanName                 string         `json:"plan_name"`
	Methodology              string         `json:"methodology"`
	StandardChargeDollar     pgtype.Numeric `json:"standard_charge_dollar"`
	StandardChargePercentage pgtype.Numeric `json:"standard_charge_percentage"`
	StandardChargeAlgorithm  pgtype.Text    `json:"standard_charge_algorithm"`
	EstimatedAmount          pgtype.Numeric `json:"estimated_amount"`
	MedianAmount             pgtype.Numeric `json:"median_amount"`
	Percentile10th           pgtype.Numeric `json:"percentile_10th"`
	Percentile90th           pgtype.Numeric `json:"percentile_90th"`
	Count                    pgtype.Text    `json:"count"`
	AdditionalNotes          pgtype.Text    `json:"additional_notes"`
}

func (q *Queries) InsertPayerCharge(ctx context.Context, arg InsertPayerChargeParams) error {
	_, err := q.db.Exec(ctx, insertPayerCharge,
		arg.StandardChargeID,
		arg.PayerName,
		arg.PlanName,
		arg.Methodology,
		arg.StandardChargeDollar,
		arg.StandardChargePercentage,
		arg.StandardChargeAlgorithm,
		arg.EstimatedAmount,
		arg.MedianAmount,
		arg.Percentile10th,
		arg.Percentile90th,
		arg.Count,
		arg.AdditionalNotes,
	)
	return err
}

const insertStandardCharge = `-- name: InsertStandardCharge :one
INSERT INTO standard_charges (
    item_id, setting, gross_charge, discounted_cash,
    minimum, maximum, modifier_codes, additional_notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertStandardChargeParams struct {
	ItemID          int32          `json:"item_id"`
	Setting         string         `json:"setting"`
	GrossCharge     pgtype.Numeric `json:"gross_charge"`
	DiscountedCash  pgtype.Numeric `json:"discounted_cash"`
	Minimum         pgtype.Numeric `json:"minimum"`
	Maximum         pgtype.Numeric `json:"maximum"`
	ModifierCodes   []string       `json:"modifier_codes"`
	AdditionalNotes pgtype.Text    `json:"additional_notes"`
}

func (q *Queries) InsertStandardCharge(ctx context.Context, arg InsertStandardChargeParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertStandardCharge,
		arg.ItemID,
		arg.Setting,
		arg.GrossCharge,
		arg.DiscountedCash,
		arg.Minimum,
		arg.Maximum,
		arg.ModifierCodes,
		arg.AdditionalNotes,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertStandardChargeItem = `-- name: InsertStandardChargeItem :one
INSERT INTO standard_charge_items (hospital_id, description, drug_unit, drug_unit_type)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertStandardChargeItemParams struct {
	HospitalID   int32          `json:"hospital_id"`
	Description  string         `json:"description"`
	DrugUnit     pgtype.Numeric `json:"drug_unit"`
	DrugUnitType pgtype.Text    `json:"drug_unit_type"`
}

func (q *Queries) InsertStandardChargeItem(ctx context.Context, arg InsertStandardChargeItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertStandardChargeItem,
		arg.HospitalID,
		arg.Description,
		arg.DrugUnit,
		arg.DrugUnitType,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listCodesByType = `-- name: ListCodesByType :many
SELECT id, code, code_type FROM codes
WHERE code_type = $1
ORDER BY code
`

func (q *Queries) ListCodesByType(ctx context.Context, codeType string) ([]Code, error) {
	rows, err := q.db.Query(ctx, listCodesByType, codeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Code
	for rows.Next() {
		var i Code
		if err := rows.Scan(&i.ID, &i.Code, &i.CodeType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandardChargeItemsByCode = `-- name: ListStandardChargeItemsByCode :many
SELECT sci.id, sci.hospital_id, sci.description, sci.drug_unit, sci.drug_unit_type, sci.created_at FROM standard_charge_items sci
JOIN item_codes ic ON ic.item_id = sci.id
JOIN codes c ON c.id = ic.code_id
WHERE c.code = $1 AND c.code_type = $2
`

type ListStandardChargeItemsByCodeParams struct {
	Code     string `json:"code"`
	CodeType string `json:"code_type"`
}

func (q *Queries) ListStandardChargeItemsByCode(ctx context.Context, arg ListStandardChargeItemsByCodeParams) ([]StandardChargeItem, error) {
	rows, err := q.db.Query(ctx, listStandardChargeItemsByCode, arg.Code, arg.CodeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandardChargeItem
	for rows.Next() {
		var i StandardChargeItem
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Description,
			&i.DrugUnit,
			&i.DrugUnitType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCode = `-- name: UpsertCode :one
INSERT INTO codes (code, code_type)
VALUES ($1, $2)
ON CONFLICT (code, code_type) DO UPDATE SET code = EXCLUDED.code
RETURNING id
`

type UpsertCodeParams struct {
	Code     string `json:"code"`
	CodeType string `json:"code_type"`
}

func (q *Queries) UpsertCode(ctx context.Context, arg UpsertCodeParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCode, arg.Code, arg.CodeType)
	var id int32
	err := row.Scan(&id)
	return id, err
}
