// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetCodeByCodeAndType(ctx context.Context, arg GetCodeByCodeAndTypeParams) (Code, error)
	GetHospitalByName(ctx context.Context, name string) (Hospital, error)
	InsertHospital(ctx context.Context, arg InsertHospitalParams) (int32, error)
	InsertItemCode(ctx context.Context, arg InsertItemCodeParams) error
	InsertModifier(ctx context.Context, arg InsertModifierParams) (int32, error)
	InsertModifierPayerInfo(ctx context.Context, arg InsertModifierPayerInfoParams) error
	InsertPayerCharge(ctx context.Context, arg InsertPayerChargeParams) error
	InsertStandardCharge(ctx context.Context, arg InsertStandardChargeParams) (int32, error)
	InsertStandardChargeItem(ctx context.Context, arg InsertStandardChargeItemParams) (int32, error)
	ListCodesByType(ctx context.Context, codeType string) ([]Code, error)
	ListStandardChargeItemsByCode(ctx context.Context, arg ListStandardChargeItemsByCodeParams) ([]StandardChargeItem, error)
	UpsertCode(ctx context.Context, arg UpsertCodeParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
